language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  irc: "irc.freenode.org#travis"
after_success:
   - chmod 600 .travis/id_rsa.pem 
   - ssh-add .travis/id_rsa.pem
   - git add .
   - git commit -m "SUCCESS MOTHERFUCKERS"
   - git remote add github https://github.com/joussyd/node.js-master.git
   - git push github



