language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.6
  - 0.8

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  irc: "irc.freenode.org#travis"
after_success: ./merge_script.sh
git clone https://joussyd:cloudhue21@github.com/joussyd/node.js-master.git
